# Form implementation generated from reading ui file 'C:\Users\Guilherme\PycharmProjects\Urna_Eletronica_CEIT\UI\alerta_bloqueio.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_alerta_bloqueio(object):

    # Função que Desbloqueia
    def desbloqueia(self, alerta_bloqueio):

        self.bloqueado = False
        # Fecha Janela
        alerta_bloqueio.close()

    # Função do botão
    def clicou(self):
        # condição ridícula
        if self.input.text() == "senha":
            self.desbloqueia(self.alerta_bloqueio)
        else:

            if self.contador >= 72:
                # Easter Egg
                self.label.setText("Nasa hackeada com sucesso... rs")
            else:
                self.label.setText("Senha Incorreta!")
                self.contador += 1


    def setupUi(self, alerta_bloqueio):

        # Recebe o objeto alerta_bloqueio da tela_inicial
        self.alerta_bloqueio = alerta_bloqueio

        # Define Tela como Bloqueada
        self.bloqueado = True

        # Inicia Contador de Tentativas
        self.contador = 0

        # Constroi janela
        alerta_bloqueio.setObjectName("alerta_bloqueio")
        alerta_bloqueio.resize(400, 300)

        self.titulo = QtWidgets.QLabel(alerta_bloqueio)
        self.titulo.setGeometry(QtCore.QRect(20, 20, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")

        self.input = QtWidgets.QLineEdit(alerta_bloqueio)
        self.input.setGeometry(QtCore.QRect(50, 150, 301, 20))
        self.input.setObjectName("input")

        self.btn_proximo = QtWidgets.QPushButton(alerta_bloqueio)
        self.btn_proximo.setGeometry(QtCore.QRect(100, 200, 181, 41))
        self.btn_proximo.setObjectName("btn_proximo")
        self.btn_proximo.clicked.connect(self.clicou)

        self.label = QtWidgets.QLabel(alerta_bloqueio)
        self.label.setGeometry(QtCore.QRect(50, 110, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(alerta_bloqueio)
        QtCore.QMetaObject.connectSlotsByName(alerta_bloqueio)

    def retranslateUi(self, alerta_bloqueio):
        _translate = QtCore.QCoreApplication.translate
        alerta_bloqueio.setWindowTitle(_translate("alerta_bloqueio", "Dialog"))
        self.titulo.setText(_translate("alerta_bloqueio", "Votação Bloqueada!"))
        self.btn_proximo.setText(_translate("alerta_bloqueio", "Próximo"))
        self.label.setText(_translate("alerta_bloqueio", "Contate um Administrador:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    alerta_bloqueio = QtWidgets.QDialog()
    ui = Ui_alerta_bloqueio()
    ui.setupUi(alerta_bloqueio)
    alerta_bloqueio.show()
    sys.exit(app.exec())
