# Form implementation generated from reading ui file 'C:\Users\Guilherme\PycharmProjects\Urna_Eletronica_CEIT\UI\tela_informacoes.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Informacoes(object):

    def fechar(self):
        self.tela_informacoes.close()

    def setupUi(self, Informacoes):

        self.tela_informacoes = Informacoes

        Informacoes.setObjectName("Informacoes")
        Informacoes.resize(800, 600)
        self.pushButton = QtWidgets.QPushButton(Informacoes)
        self.pushButton.setGeometry(QtCore.QRect(470, 510, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.fechar)
        self.label = QtWidgets.QLabel(Informacoes)
        self.label.setGeometry(QtCore.QRect(270, 10, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Informacoes)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Informacoes)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Informacoes)
        self.label_4.setGeometry(QtCore.QRect(40, 270, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Informacoes)
        self.label_5.setGeometry(QtCore.QRect(40, 330, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Informacoes)
        self.label_6.setGeometry(QtCore.QRect(40, 390, 711, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Informacoes)
        QtCore.QMetaObject.connectSlotsByName(Informacoes)

    def retranslateUi(self, Informacoes):
        _translate = QtCore.QCoreApplication.translate
        Informacoes.setWindowTitle(_translate("Informacoes", "Dialog"))
        self.pushButton.setText(_translate("Informacoes", "PRONTO"))
        self.label.setText(_translate("Informacoes", "Informações:"))
        self.label_2.setText(_translate("Informacoes", "1 - Insira seu Token de Aluno"))
        self.label_3.setText(_translate("Informacoes", "2 - Escolha a Chapa Em Que Deseja Votar"))
        self.label_4.setText(_translate("Informacoes", "3 - Confirme os Candidatos da Chapa"))
        self.label_5.setText(_translate("Informacoes", "4 - Clique em Votar"))
        self.label_6.setText(_translate("Informacoes", "5 - Clique em Finalizar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Informacoes = QtWidgets.QDialog()
    ui = Ui_Informacoes()
    ui.setupUi(Informacoes)
    Informacoes.show()
    sys.exit(app.exec())
