# Form implementation generated from reading ui file 'C:\Users\Guilherme\PycharmProjects\Urna_Eletronica_CEIT\UI\tela_inicial.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from tela_voto import Ui_tela_voto


def valida_token(token):
    # Atribui o arquivo txt com os tokens para a variável arquivo
    with open("Recursos/lista_tokens.txt", "r") as arquivo:

        # Linhas é uma lista[] onde cada elemento é uma linha do arquivo
        linhas = arquivo.readlines()

        # Se encontrar o token inserido pelo usuário dentro da lista de tokens retorna VERDADEIRO e fecha o arquivo
        for linha in linhas:
            if token == linha.strip():
                arquivo.close()
                return True

class Ui_Dialog(object):

    # Função que implementa a ação de clicar no botão
    def clicou(self):

        # Verifica entrada do usuário
        if self.input.text() == "":
            print("Insira um Token!")
        else:
            print("Token: ", self.input.text())
            if valida_token(self.input.text()):
                print("Token Válido!")

                # Abre a tela_voto
                self.chama_tela_voto()

                # Esconde a janela
                tela_inicial.hide()
            else:
                print("Token Inválido!")

    # Função que chama a tela_voto
    def chama_tela_voto(self):
        # Cria Janela
        self.janela = QtWidgets.QDialog()
        # Cria Interface
        self.ui = Ui_tela_voto()
        # Chama o Método de "inflar" a interface na janela passando o token como parâmetro
        self.ui.setupUi(self.janela)
        # Passa o Token como parâmetro para a tela_voto
        self.ui.label_2.setText(self.ui.label_2.text() + self.input.text())
        # Exibe Janela
        self.janela.show()
        # Esconde tela_inicial
        tela_inicial.hide()



    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(866, 600)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\Logo CEIT.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.titulo = QtWidgets.QLabel(Dialog)
        self.titulo.setGeometry(QtCore.QRect(290, 30, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 220, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.input = QtWidgets.QLineEdit(Dialog)
        self.input.setGeometry(QtCore.QRect(290, 300, 541, 60))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.input.setFont(font)
        self.input.setMaxLength(12)
        self.input.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.input.setObjectName("input")
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(290, 390, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        self.btn.clicked.connect(self.clicou)

        self.logo = QtWidgets.QLabel(Dialog)
        self.logo.setGeometry(QtCore.QRect(10, 0, 230, 230))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("UI\\Logo CEIT.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "URNA CEIT"))
        self.titulo.setText(_translate("Dialog", "ELEIÇÕES GRÊMIO ESTUDANTIL CEIT - 2022"))
        self.label.setText(_translate("Dialog", "Insira seu Token de aluno:"))
        self.input.setText(_translate("Dialog", "OdrvK3AnAM0v"))
        self.btn.setText(_translate("Dialog", "Próximo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_inicial = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(tela_inicial)
    tela_inicial.show()
    sys.exit(app.exec())
