# Form implementation generated from reading ui file 'C:\Users\Guilherme\PycharmProjects\Urna_Eletronica_CEIT\UI\tela_resultados.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(866, 600)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\Logo CEIT.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.titulo = QtWidgets.QLabel(Dialog)
        self.titulo.setGeometry(QtCore.QRect(290, 30, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(290, 110, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_finalizar = QtWidgets.QPushButton(Dialog)
        self.btn_finalizar.setGeometry(QtCore.QRect(600, 500, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_finalizar.setFont(font)
        self.btn_finalizar.setObjectName("btn_finalizar")
        self.logo = QtWidgets.QLabel(Dialog)
        self.logo.setGeometry(QtCore.QRect(10, 0, 230, 230))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("UI\\Logo CEIT.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.lblChapa1 = QtWidgets.QLabel(Dialog)
        self.lblChapa1.setGeometry(QtCore.QRect(290, 270, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblChapa1.setFont(font)
        self.lblChapa1.setObjectName("lblChapa1")
        self.lblChapa2 = QtWidgets.QLabel(Dialog)
        self.lblChapa2.setGeometry(QtCore.QRect(290, 330, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblChapa2.setFont(font)
        self.lblChapa2.setObjectName("lblChapa2")
        self.lblChapa3 = QtWidgets.QLabel(Dialog)
        self.lblChapa3.setGeometry(QtCore.QRect(290, 390, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblChapa3.setFont(font)
        self.lblChapa3.setObjectName("lblChapa3")
        self.lblVencedor = QtWidgets.QLabel(Dialog)
        self.lblVencedor.setGeometry(QtCore.QRect(30, 270, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblVencedor.setFont(font)
        self.lblVencedor.setObjectName("lblVencedor")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "URNA CEIT"))
        self.titulo.setText(_translate("Dialog", "ELEIÇÕES GRÊMIO ESTUDANTIL CEIT - 2022"))
        self.label.setText(_translate("Dialog", "Resultados:"))
        self.btn_finalizar.setText(_translate("Dialog", "Finalizar"))
        self.lblChapa1.setText(_translate("Dialog", "Chapa 1:"))
        self.lblChapa2.setText(_translate("Dialog", "Chapa 2:"))
        self.lblChapa3.setText(_translate("Dialog", "Chapa 3:"))
        self.lblVencedor.setText(_translate("Dialog", "Vencedor: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
